### ISSUE TITLE
Random movement but no action

### ISSUE THREAD

**Issue by gauravyadav26** [HCA97/jw_bot#5]
After marking top and bottom cursor starts to move and console starts logging and it keep on happening but nothing happens in the game.

**Comment by HCA97** [comment]
Hi @gauravyadav26,

What do you mean when you say nothing happens? Does the screen rotate after a while? What messages do you see in the logs? This could be a timing issue or a problem with the detection algorithm.

If it's a timing issue, you can check out this thread: (https://github.com/HCA97/jw_bot/issues/4). Unfortunately, timing problems can be a bit complicated because of differences in internet and hardware speeds.

If the detection algorithm isn't working well, you'll need to adjust the following RGB values:
- https://github.com/HCA97/jw_bot/blob/8345041bb94e58397394cb85ce39f12daa6e3696/jw_bot.py#L67C9-L68C11
- https://github.com/HCA97/jw_bot/blob/8345041bb94e58397394cb85ce39f12daa6e3696/jw_bot.py#L82

Additionally, you can check out this thread for some tips and tricks https://github.com/HCA97/jw_bot/issues/2#issuecomment-1698020617

**Comment by gauravyadav26** [comment]
It keeps saying nothing here and sometimes says Dino found 15(some number). But nothing happens in the game — just cursor movement.

I will try color correction.

**Comment by HCA97** [comment]
Hi,

If the cursor moves but nothing happens, even when changing the view, it seems like a timing issue.

Additionally, you might have some detection issues as well. Since it's Lunar New Year, they might have updated the visuals of the supply drops, coin chests, and dinosaurs.

**Comment by gauravyadav26** [comment]
I have tried to increase the time. Now when changing the view it throws this error

`Traceback (most recent call last):
  File "C:\Users\gaura\Desktop\jw_bot-main\jw_bot-main\main.py", line 55, in <module>
    bot.change_view()
  File "C:\Users\gaura\Desktop\jw_bot-main\jw_bot-main\jw_bot.py", line 565, in change_view
    pos = self.locate_x_button(background)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gaura\Desktop\jw_bot-main\jw_bot-main\jw_bot.py", line 225, in locate_x_button
    button_color = self.x_button_color
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'x_button_color'`

**Comment by HCA97** [comment]
Hi. I think you commented out the following line https://github.com/HCA97/jw_bot/blob/8345041bb94e58397394cb85ce39f12daa6e3696/jw_bot.py#L79

**Comment by gauravyadav26** [comment]
May I know what is this line for
` self.gmap_loc_color = (200, 0, 0, 255, 70, 60)  `

**Comment by HCA97** [comment]
Hi, it is (r_min, g_min, b_min, r_max, g_max, b_max):https://github.com/HCA97/jw_bot/blob/8345041bb94e58397394cb85ce39f12daa6e3696/jw_bot.py#L515

**Comment by gauravyadav26** [comment]
I meant what gmap_loc_color is actually doing

**Comment by HCA97** [comment]
Hi,

Oh, I misunderstood you. `gmap_loc_color` refers to the color of the Google Map location, specifically the red pin:

![Google Map Location](https://support.bluestacks.com/hc/article_attachments/4407451165069/1A.png)

Yes, initially, I attempted to use multiple figures to detect different loading screens. But, at the end, I used simpler checking methods. I only check for the loading screen featuring the shooting Dino.

**Comment by gauravyadav26** [comment]
Thank you for the help. I tried everything but it does not do anything for me. I'm not able to make it perform any action at all.

**Comment by HCA97** [comment]
Hmm, that's interesting. Perhaps something changed since the last time I used it. Unfortunately, I don't have access to a Windows computer right now. I'll check it when I have access, which should be possible next week.

**Comment by gauravyadav26** [comment]
Did you get a chance to have a look?

**Comment by HCA97** [comment]
Hi,

Yes. In my computer it works, at least it can change view, click thins. 

There was some accuracy issue with supply drops due to wrong RGB values. And I realized game becomes super laggy. Can't say for sure if it's because my laptop is getting old, something's up with Bluestacks, or if the game itself getting slower.

Anyway, I fixed the supply drop coloring and extended some sleep durations. Maybe this will help. You can check out what I changed in this pull request (https://github.com/HCA97/jw_bot/pull/6).

If this doesnt work, I'd suggest increasing all the `time.sleep` values, maybe adding a second. If that still doesn't work, I'm not sure what else might be causing the issue in your case.

**Comment by gauravyadav26** [comment]
Did all of the above but still nothing. Could it also be some dependency issue?

**Comment by HCA97** [comment]
If it was dependecny issue you should get error about some package is missing. But it is possible. 

Is there a reason you mention the dependency issue?

My environment is:
- Python 3.9
- Bluestack 4.250
- Result of pip freeze:
  ```
  contourpy==1.2.0
  cycler==0.12.1
  fonttools==4.49.0
  imageio==2.34.0
  importlib-resources==6.1.2
  keyboard==0.13.5
  kiwisolver==1.4.5
  lazy-loader==0.3
  matplotlib==3.8.3
  MouseInfo==0.1.3
  networkx==3.2.1
  numpy==1.26.4
  packaging==23.2
  Pillow==9.5.0
  PyAutoGUI==0.9.54
  PyGetWindow==0.0.9
  PyMsgBox==1.0.9
  pyparsing==3.1.1
  pyperclip==1.8.2
  PyRect==0.2.0
  PyScreeze==0.1.30
  pytesseract==0.3.10
  python-dateutil==2.8.2
  pytweening==1.2.0
  scikit-image==0.22.0
  scipy==1.12.0
  six==1.16.0
  tifffile==2024.2.12
  zipp==3.17.0
  ```
- tesseract version:
  ```
  tesseract v5.3.1.20230401
   leptonica-1.83.1
    libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.13 : libwebp 1.3.0 : libopenjp2 2.5.0
   Found AVX2
   Found AVX
   Found FMA
   Found SSE4.1
   Found libarchive 3.6.2 zlib/1.2.13 liblzma/5.2.9 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2
   Found libcurl/8.0.1 Schannel zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0
  ```

**Comment by gauravyadav26** [comment]
I mentioned dependencies as it does not even change the view, which I thought it should.

My environment is:

- Python 3.11
- Bluestack 5.12

Can this cause issues?

**Comment by HCA97** [comment]
Hi,

I tried using `Bluestack 5.20`, and it still works on my computer. I'm not sure if Python versions will make a difference, but you can try downgrading it to see if it helps.

By the way, to change the view, the bot uses the scroll button. Make sure you can change the view by scrolling. You can find the code for this here: [link to code snippet](https://github.com/HCA97/jw_bot/blob/76e745104878525685bebd46ac8c8f2a81c6317c/jw_bot.py#L580C9-L580C29).

Additionally, could you try debugging it using `test_action.py` to get a sense of what bot sees? You can try performing actions like collecting supply drops or shooting a dinosaur. You can find the debugging script here: [link to debugging script](https://github.com/HCA97/jw_bot/blob/76e745104878525685bebd46ac8c8f2a81c6317c/test_action.py#L104C1-L107C46).

Keep in mind that when shooting a dinosaur, you have to launch the drone first for the bot. It should look something like this:
![image](https://github.com/HCA97/jw_bot/assets/24678502/7319b1b3-d046-422a-9860-7bd2fb6a2897)

**Comment by gauravyadav26** [comment]
Thanks for the help got it working. Any thoughts on how to improve its shooting?

**Comment by HCA97** [comment]
Glad it's working now. How did you manage to fix the issue?

As for improving shooting, it might not be easy. We might need more efficient code to run the tracking more smoothly, possibly using multiprocessing, or a better algorithm, perhaps using reinforcement learning. However, if you're interested, you can experiment with hyperparameters:

- D: distance to center circle
- S: slow down speed for the Dino to avoid overshooting
- h1, h2, h3: lower the battery increase the D (h1), lower the battery look more ahead (h2), and lower the battery slow down much slower (h3). Note that 0 < h3 <= S.
- ms: how fast the mouse moves
- v_max: maximum velocity, useful for calculating the trajectory of the Dino

The algorithm used is the Purse, Flee, Evade algorithm. I recommend watching the explanation to understand the parameters better: [YouTube link](https://youtu.be/Q4MU7pkDYmQ?feature=shared)

**Comment by gauravyadav26** [comment]
It was a rights issue (my blue stacks run with administrative privileges so I needed to run the cmd as administrator. Stupid thing).

I will try my hands on the shooting and will update you if I make any progress.

**Comment by darshanraok** [comment]
@HCA97 can you implement this [bot] directly for Android devices, root permissions can also be utilized

**Comment by HCA97** [comment]
@darshanraok Sorry for the delayed response; I just saw your message.

Regarding your request, I am not experienced with Android devices or app development, so I’m not entirely sure where to start :) As far as I know, you cannot run Python code directly on Android devices, so you might need to rewrite it in another language, maybe in Java, that is compatible with Android. Additionally, the libraries I used for clicking, taking screenshots, and image processing may not work on Android.

Sorry, I’m not sure I can provide much help with running the bot on Android devices directly.
